t = read.table("household_power_consumption.txt", skip = 66637, nrows = 2880, sep = ";")
names(t) = c("Date", "Time", "Glob_act_power", "Glob_react_pow", "volt", "inten", "m1", "m2", "m3")

png(filename = "plot3.png")
#windows()
dts = as.POSIXct(paste(t$Date, t$Time), format = "%d/%m/%Y %H:%M:%S")
plot(dts, t$m1, type = 'l', col = "black", ylab = " ", xlab = "")
lines(dts, t$m2, type = 'l', col = "red")
lines(dts, t$m3, type = 'l', col = "blue")
title(xlab = "", ylab = "energy sub metering")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"))
dev.off()